'''Create list of language code and string to identify translation line.

This was created for almost all languages on the English Wiktionary 'apple'
page (on 03Aug2026). Languages were omitted if I thought the line with the
translation couldn't be identified from just the line. For example, both
Serbian and Croatian are omitted because they start with the strings
':* Cyrllic:' and ':* Latin:', respectively, and at least ':* Cyrillic'
will conflict with the subheading for Old Church Slavonic, etc.
'''

LANGUAGES = [
('abq','* Abaza:'),
('abe','* Abenaki:'),
('ab','* Abkhaz:'),
('af','* Afrikaans:'),
('ain','* Ainu:'),
('akk','* Akkadian:'),
('akz','* Alabama:'),
('sq','* Albanian:'),
('ale','* Aleut:'),
('avd','* Alviri-Vidari:'),
('am','* Amharic:'),
('ami','* Amis:'),
('ar','* Arabic:'),
('arq','*: Algerian Arabic:'),
('arz','*: Egyptian Arabic:'),
('afb','*: Gulf Arabic:'),
('acw','*: Hijazi Arabic:'),
('an','* Aragonese:'),
('aii','*: Assyrian Neo-Aramaic:'),
('syc','*: Classical Syriac:'),
('aqc','* Archi:'),
('hy','* Armenian:'),
('rup','* Aromanian:'),
('as','* Assamese:'),
('ast','* Asturian:'),
('av','* Avar:'),
('az','* Azerbaijani:'),
('bdr','*: West Coast Bajau:'),
('bal','* Baluchi:'),
('ba','* Bashkir:'),
('eu','* Basque:'),
('bbl','* Bats:'),
('be','* Belarusian:'),
('bn','* Bengali:'),
('bho','* Bhojpuri:'),
('bcl','*: Central Bikol:'),
('bi','* Bislama:'),
('bla','* Blackfoot:'),
('br','* Breton:'),
('bdk','* Budukh:'),
('bg','* Bulgarian:'),
('bnn','* Bunun:'),
('my','* Burmese:'),
('bua','* Buryat:'),
('rue','* Carpathian Rusyn:'),
('ca','* Catalan:'),
('ceb','* Cebuano:'),
('tzm','* Central Atlas Tamazight:'),
('ce','* Chechen:'),
('chr','* Cherokee:'),
('chy','* Cheyenne:'),
('yue','*: Cantonese:'),
('dng','*: Dungan:'),
('cdo','*: Eastern Min:'),
('gan','*: Gan:'),
('hak','*: Hakka:'),
('nan-hbl','*: Hokkien:'),
('cjy','*: Jin:'),
('cmn','*: Mandarin:'),
('mnp','*: Northern Min:'),
('wuu','*: Wu:'),
('hsn','*: Xiang:'),
('cv','* Chuvash:'),
('kdb','*: East Circassian:'),
('ady','*: West Circassian:'),
('zdj','*: Ngazidja Comorian:'),
('cop','* Coptic:'),
('kw','* Cornish:'),
('crh','* Crimean Tatar:'),
('cs','* Czech:'),
('da','* Danish:'),
('dar','* Dargwa:'),
('dv','* Dhivehi:'),
('dtp','*: Central Dusun:'),
('nl','* Dutch:'),
('dz','* Dzongkha:'),
('dphw','* Egyptian:'),
('eppel','* Elfdalian:'),
('egl','* Emilian:'),
('myv','* Erzya:'),
('eo','* Esperanto:'),
('et','* Estonian:'),
('fax','* Fala:'),
('fo','* Faroese:'),
('fj','* Fijian:'),
('hif','* Fiji Hindi:'),
('fi','* Finnish:'),
('fr','* French:'),
('ofs','*: Old Frisian:'),
('stq','*: Saterland Frisian:'),
('fy','*: West Frisian:'),
('fur','* Friulian:'),
('gag','* Gagauz:'),
('gl','* Galician:'),
('ka','* Georgian:'),
('de','* German:'),
('bar','*: Bavarian:'),
('gmw-cfr','*: Central Franconian:'),
('goh','*: Old High German:'),
('el','* Greek:'),
('kl','* Greenlandic:'),
('gug','*: Paraguayan Guarani:'),
('gu','* Gujarati:'),
('ht','* Haitian Creole:'),
('haw','* Hawaiian:'),
('he','* Hebrew:'),
('hi','* Hindi:'),
('hu','* Hungarian:'),
('hrx','* Hunsrik:'),
('iba','* Iban:'),
('is','* Icelandic:'),
('io','* Ido:'),
('ilo','* Ilocano:'),
('id','* Indonesian:'),
('izh','* Ingrian:'),
('inh','* Ingush:'),
('ia','* Interlingua:'),
('iu','* Inuktitut:'),
('ga','* Irish:'),
('mga','*: Middle Irish:'),
('sga','*: Old Irish:'),
('it','* Italian:'),
('jam','* Jamaican Creole:'),
('ja','* Japanese:'),
('jv','* Javanese:'),
('jje','* Jeju:'),
('xdq','* Kaitag:'),
('xal','* Kalmyk:'),
('kn','* Kannada:'),
('krc','* Karachay-Balkar:'),
('kaa','* Karakalpak:'),
('krl','* Karelian:'),
('ks','* Kashmiri:'),
('csb','* Kashubian:'),
('ckv','* Kavalan:'),
('kk','* Kazakh:'),
('klj','* Khalaj:'),
('km','* Khmer:'),
('koi','*: Komi-Permyak:'),
('ko','* Korean:'),
('kum','* Kumyk:'),
('ckb','*: Central Kurdish:'),
('lki','*: Laki:'),
('kmr','*: Northern Kurdish:'),
('sdh','*: Southern Kurdish:'),
('fkv','* Kven:'),
('ky','* Kyrgyz:'),
('lad','* Ladino:'),
('lbe','* Lak:'),
('lo','* Lao:'),
('ltg','* Latgalian:'),
('la','* Latin:'),
('lv','* Latvian:'),
('lez','* Lezgi:'),
('lij','* Ligurian:'),
('li','* Limburgish:'),
('lt','* Lithuanian:'),
('liv','* Livonian:'),
('lmo','* Lombard:'),
('nds-de','*: German Low German:'),
('khb','* Lü:'),
('lb','* Luxembourgish:'),
('mk','* Macedonian:'),
('mg','* Malagasy:'),
('ms','* Malay:'),
('ml','* Malayalam:'),
('mt','* Maltese:'),
('mnc','* Manchu:'),
('gv','* Manx:'),
('mi','* Māori:'),
('mrw','* Maranao:'),
('mr','* Marathi:'),
('mhr','*: Eastern Mari:'),
('mrc','* Maricopa:'),
('mh','* Marshallese:'),
('mfe','* Mauritian Creole:'),
('mel','*: Central Melanau:'),
('enm','* Middle English:'),
('xmf','* Mingrelian:'),
('mwl','* Mirandese:'),
('mhn','* Mòcheno:'),
('moh','* Mohawk:'),
('mdf','* Moksha:'),
('nah','* Nahuatl:'),
('nv','* Navajo:'),
('nap','* Neapolitan:'),
('ne','* Nepali:'),
('new','* Newar:'),
('nog','* Nogai:'),
('nrf','* Norman:'),
('nb','*: Bokmål:'),
('nn','*: Nynorsk:'),
('nwy','* Nottoway-Meherrin:'),
('oc','* Occitan:'),
('or','* Odia:'),
('oj','* Ojibwe:'),
('orv','* Old East Slavic:'),
('ang','* Old English:'),
('roa-ole','* Old Leonese:'),
('non','* Old Norse:'),
('prg','* Old Prussian:'),
('xme-ott','* Old Tati:'),
('om','* Oromo:'),
('os','* Ossetian:'),
('pwn','* Paiwan:'),
('rsk','* Pannonian Rusyn:'),
('pap','* Papiamentu:'),
('ps','* Pashto:'),
('pnh','* Penrhyn:'),
('prs','*: Dari:'),
('fa-ira','*: Iranian Persian:'),
('pcd','* Picard:'),
('pmd','* Piedmontese:'),
('pdt','* Plautdietsch:'),
('pox','* Polabian:'),
('pl','* Polish:'),
('pt','* Portuguese:'),
('pa','*: Gurmukhi:'),
('pnb','*: Western Punjabi:'),
('qu','* Quechua:'),
('rar','* Rarotongan:'),
('rcf','* Réunion Creole French:'),
('rhg','* Rohingya:'),
('rgn','* Romagnol:'),
('rom','* Romani:'),
('ro','* Romanian:'),
('rm','* Romansh:'),
('ru','* Russian:'),
('rw','* Rwanda-Rundi:'),
('se','*: Northern Sami:'),
('sms','*: Skolt Sami:'),
('sm','* Samoan:'),
('sa','* Sanskrit:'),
('sc','* Sardinian:'),
('sco','* Scots:'),
('gd','* Scottish Gaelic:'),
('crs','* Seychellois Creole:'),
('xsr','* Sherpa:'),
('scn','* Sicilian:'),
('sd','* Sindhi:'),
('si','* Sinhalese:'),
('sk','* Slovak:'),
('sl','* Slovene:'),
('so','* Somali:'),
('dsb','*: Lower Sorbian:'),
('hsb','*: Upper Sorbian:'),
('st','* Sotho:'),
('es','* Spanish:'),
('xsv','* Sudovian:'),
('su','* Sundanese:'),
('sva','* Svan:'),
('sw','* Swahili:'),
('sv','* Swedish:'),
('syl','* Sylheti:'),
('tab','* Tabasaran:'),
('tl','* Tagalog:'),
('ty','* Tahitian:'),
('tg','* Tajik:'),
('tly','* Talysh:'),
('ta','* Tamil:'),
('roa-tar','* Tarantino:'),
('trv','* Taroko:'),
('ttt','* Tat:'),
('tt','* Tatar:'),
('te','* Telugu:'),
('tet','* Tetum:'),
('th','* Thai:'),
('bo','* Tibetan:'),
('ti','* Tigrinya:'),
('tli','* Tlingit:'),
('tkl','* Tokelauan:'),
('to','* Tongan:'),
('ts','* Tsonga:'),
('tsu','* Tsou:'),
('tr','* Turkish:'),
('ota','*: Ottoman Turkish:'),
('tk','* Turkmen:'),
('udi','* Udi:'),
('udm','* Udmurt:'),
('uga','* Ugaritic:'),
('uk','* Ukrainian:'),
('unm','* Unami:'),
('ur','* Urdu:'),
('ug','* Uyghur:'),
('uz','* Uzbek:'),
('ve','* Venda:'),
('vec','* Venetan:'),
('vi','* Vietnamese:'),
('wym','* Vilamovian:'),
('vo','* Volapük:'),
('vro','* Võro:'),
('wa','* Walloon:'),
('war','* Waray-Waray:'),
('cy','* Welsh:'),
('win','* Winnebago:'),
('wo','* Wolof:'),
('xh','* Xhosa:'),
('yai','* Yaghnobi:'),
('sah','* Yakut:'),
('yi','* Yiddish:'),
('yo','* Yoruba:'),
('yua','* Yucatec Maya:'),
('esu',"* Yup'ik:"),
('yur','* Yurok:'),
('zza','* Zazaki:'),
('za','* Zhuang:'),
('zu','* Zulu:'),
('zun','* Zuni:'),
]
